spring:
  application:
    name: LoggingWithLevelsJsonLogsAndMdc
  datasource:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
    name: database
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
