spring.application.name=RateLimitingAndMonitoring
server.port=8100
#database
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.generate-unique-name=false
spring.datasource.name=database
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#actuator
management.endpoints.web.exposure.include=health,metrics
management.health.db.enabled=true
management.health.redis.enabled=true
