spring.application.name=ECommerceProductAggregator

api.url.euro-net-url=http://localhost:8100/EuroNet
api.url.media-expert-url=http://localhost:8100/MediaExpert
api.url.media-markt-url=http://localhost:8100/MediaMarkt
api.url.nbp-url=https://api.nbp.pl/api/exchangerates/rates/a
