spring.application.name=security
jwt.secret=${JWT.SECRET}
jwt.access.expiration=900
jwt.refresh.expiration=604800

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

init.admin.email=${INIT.ADMIN.EMAIL}
init.admin.password=${INIT.ADMIN.PASSWORD}
